calc : main.o add1.o div1.o printVal.o
	g++ main.o add1.o div1.o printVal.o

main.o : main.cpp
	g++ -c main.cpp

add1.o : add1.cpp
	g++ -c add1.cpp 

div1.o : div1.cpp
	g++ -c div1.cpp 

printVal.o : printVal.cpp
	g++ -c printVal.cpp

